# ________________________________________________________________________________________________
#
#       ██╗░░░██╗███████╗██╗░░██╗███╗░░░███╗░█████╗░░██████╗
#       ██║░░░██║██╔════╝╚██╗██╔╝████╗░████║██╔══██╗██╔════╝
#       ╚██╗░██╔╝█████╗░░░╚███╔╝░██╔████╔██║██║░░██║╚█████╗░
#       ░╚████╔╝░██╔══╝░░░██╔██╗░██║╚██╔╝██║██║░░██║░╚═══██╗
#       ░░╚██╔╝░░███████╗██╔╝╚██╗██║░╚═╝░██║╚█████╔╝██████╔╝
#       ░░░╚═╝░░░╚══════╝╚═╝░░╚═╝╚═╝░░░░░╚═╝░╚════╝░╚═════╝░
#
# VexmosNET®, propriedade de Vexmos® e não afiliado à Mojang AB.
# Todos os direitos reservados © 2024.
# ________________________________________________________________________________________________
mysql:
  host: "us5.strawberry.urubuhost.com"
  name: "s1506_system"
  username: "u1506_22IRAKX8S7"
  password: "qg6sXtcsCfmMF+yvCH1tk6t^"
  port: "3306"