# ________________________________________________________________________________________________
#
#       ██╗░░░██╗███████╗██╗░░██╗███╗░░░███╗░█████╗░░██████╗
#       ██║░░░██║██╔════╝╚██╗██╔╝████╗░████║██╔══██╗██╔════╝
#       ╚██╗░██╔╝█████╗░░░╚███╔╝░██╔████╔██║██║░░██║╚█████╗░
#       ░╚████╔╝░██╔══╝░░░██╔██╗░██║╚██╔╝██║██║░░██║░╚═══██╗
#       ░░╚██╔╝░░███████╗██╔╝╚██╗██║░╚═╝░██║╚█████╔╝██████╔╝
#       ░░░╚═╝░░░╚══════╝╚═╝░░╚═╝╚═╝░░░░░╚═╝░╚════╝░╚═════╝░
#
# VexmosNET®, propriedade de Vexmos® e não afiliado à Mojang AB. Todos os direitos reservados © 2024.
#
# ________________________________________________________________________________________________
#
name: VexmosNET
version: 1.0
main: net.vexmos.spigot.VexmosNET
authors: [nevesbr6, spirit]
description: ©2025 Vexmos, Inc.
website: www.vexmos.net
